dist: trusty
sudo: required

services:
  - docker
  
before_install:
- docker pull phusion/holy-build-box-64:latest

script:
- docker run -t -i --rm -v ${TRAVIS_BUILD_DIR}:/io phusion/holy-build-box-64:latest bash /io/scripts/linux-build-helper.sh
